# All exercises list
ALL_EXERCISES = [
    'https://www.youtube.com/shorts/eYLPbzC1Xjs',
    'https://www.youtube.com/shorts/UOyAHw0Ne08',
    'https://youtube.com/shorts/DtOnHQoVkYU',
    'https://youtu.be/zVgrqY5ECeo',
    'https://youtube.com/shorts/LmNcz9vy2ok',
    'https://youtube.com/shorts/Z2MhvccsvuE',
    'https://youtube.com/shorts/y4ToTbDFD2g',
    'https://youtube.com/shorts/Ghur7a-uBIw',
    'https://youtube.com/shorts/w0Me5DXFdx4',
    'https://youtube.com/shorts/tFqPGwjnlUY',
    'https://youtube.com/shorts/qMjyFu-22dA',
    'https://youtube.com/shorts/EDMzoe1Lpz4',
    'https://youtube.com/shorts/5GmJbQRj3RY',
    'https://youtube.com/shorts/y0duVVnwthA',
    'https://youtube.com/shorts/sLNUEMatAcQ?feature=share',
    'https://youtube.com/shorts/lDEvck9nQsA?feature=share',
    'https://youtube.com/shorts/WDNsSGOsodw?feature=share',
    'https://youtube.com/shorts/HKNM--vxXl0',
'https://youtube.com/shorts/ofB6Uuw6FG0',
'https://youtube.com/shorts/1nuULE0LOsU',
'https://youtube.com/shorts/tSfYGisrkLo',
'https://www.youtube.com/shorts/PQD0ZlLiDEg',
'https://youtube.com/shorts/QUR4mccMmho?feature=share',
'https://youtube.com/shorts/gQhpzRD4fNI?feature=share',
'https://youtube.com/shorts/gQNR0qjFgTg?feature=share',
'https://youtube.com/shorts/udgP-HZ-BPU?feature=share',
'https://youtube.com/shorts/uKqxrMMc1wQ',
'https://youtube.com/shorts/JtT7ZZ4jMN4',
'https://youtube.com/shorts/LkooGlXo3-k',
'https://youtube.com/shorts/fY2tBsiH1e4?feature=share',
'https://youtube.com/shorts/ahc4Ls1tZe0?feature=share',
'https://youtube.com/shorts/9peqAqQcYdc?feature=share',
'https://youtube.com/shorts/pIBbyu4WUI4',
'https://youtube.com/shorts/1hWbK820VFA?feature=share',
'https://youtube.com/shorts/prI8NAj7FKU?feature=share',
'https://youtube.com/shorts/LvEMx49KIdo',
'https://youtube.com/shorts/9LCQFNvmkg0?feature=share',
'https://youtube.com/shorts/Yi-j91p0A8M?feature=share',
'https://youtube.com/shorts/7ToZVrEZZH0?feature=share',


]
